name: "cosanostr CI"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - run: bundle exec rake
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bundle exec rails db:schema:load
      - name: Precompile assets
        run: bundle exec rake assets:precompile
      # Add or replace test runners here
      - name: Run tests
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
          RAILS_ENV: test
        run: bundle exec rspec
